### ISSUE TITLE
Long preview screen (blank purple screen) in the app sample start on android 

### ISSUE THREAD

**Issue by IdanLevi** [NaylahProject/Naylah#2]
Any thoughts on how to present a splash screen **correctly** on android instead of the purple preview screen?

Now what happens is the purple screen is shown while all the dlls load, and only then the SplashPage (to load things) appears.

**Comment by angusbreno** [comment]
There is 2 concepts about "splash screen" here.

1. The first one (blank purple screen) is the "Android" splash, where it loads the app it-self not 'your code' yet. In default that screen it's white or black, but to keep it more beautiful i've puttud this https://github.com/NaylahProject/Naylah/blob/master/Naylah.SampleApp/Naylah.SampleApp.Droid/Resources/values/style.xml#L14 wich makes the color background in splash, showing u can change anytime u want. There is another way, a little expensive but more beautiful too, that is create a SplashActivity in android project to load with custom content (logos, etc) before MainActivity.

2. The "your code" splash. I've create second splash to show a sample of app phases. What u mean "with app phases"? Assuming that you app can change the navigation logic and everything splash screen in this case have a purpose to change the phases or maybe, u want to load something there? maybe u don't need that? It's not mandatory. It's just a sample. 

Now, all this makes sense?

**Comment by IdanLevi** [comment]
Thanks for the answer!
I'll try to implement it in the next few days and report back.

**Comment by angusbreno** [comment]
What u need implement?

**Comment by IdanLevi** [comment]
A splash activity with a background and image before the main activity.

**Comment by angusbreno** [comment]
There u have it
https://gist.github.com/angusbreno/5626decb9f917e238b0d16a4355906b5

**Comment by IdanLevi** [comment]
Worked perfectly. Thank you!

**Comment by angusbreno** [comment]
Please, feel free to make a PR into SampleApp with this kind of splash too.
