### ISSUE TITLE
Help regarding intergrating Azure App Service authentication on a Naylah sample app based app

### ISSUE THREAD

**Issue by IdanLevi** [NaylahProject/Naylah#5]
I'm doing my final project for my degree and using Naylah's sample app as a base.

I had a previous implementation where I used the following guide as a reference for implementing authentication for my app:

https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-xamarin-forms-get-started-users/

After migrating to a new Naylah based UI, I started having a problem I can't figure out on iOS (Android works fine).

When I click the Facebook login button, the 'Authenticate' method on 'AppDelegate.cs' gets stuck on the call:
var user = await CurrentClient.LoginAsync(UIApplication.SharedApplication.KeyWindow.RootViewController, MobileServiceAuthenticationProvider.Facebook);

Do you have any idea why does it happen?

**Comment by angusbreno** [comment]
Can u share your project somewhere?

**Comment by IdanLevi** [comment]
Hi, apparently it was my bad....
The problem is App.Init(this) was not in the right order in AppDelegate. :(
That fixed it, thanks a lot!
