### ISSUE TITLE
Help Adding ToolbarItem

### ISSUE THREAD

**Issue by GalFriD** [NaylahProject/Naylah#6]
I have a page in my app that has a floating action button for Android. I need to add a Toolbar button instead for iOS but I couldn't figure out how to do it. What do I need to do?
I tried this code in my contentpage:

if(Device.OS == TargetPlatform.iOS)
{
       ToolBarItems.Add(new ToolBarItem{Text="1", Priority = 0, Order = ToolBarItemOrder.Primary});
}

and it doesnt work. 
I tried to make renderer as well in the ios project and still doenst work..

have any idea?
thx alot

**Comment by erickriva** [comment]
Was added on SampleApp a similar behavior (using Floating Action Button and ToolbarItems), give a check on it ;)

[https://github.com/NaylahProject/Naylah/blob/master/Naylah.SampleApp/Naylah.SampleApp/Views/AnotherPage.cs#L34](https://github.com/NaylahProject/Naylah/blob/master/Naylah.SampleApp/Naylah.SampleApp/Views/AnotherPage.cs#L34)

**Comment by angusbreno** [comment]
Can i close?

**Comment by GalFriD** [comment]
yes..thx
