### ISSUE TITLE
SampleApp not deploying on iOS

### ISSUE THREAD

**Issue by GalFriD** [NaylahProject/Naylah#7]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to resolve assembly: 'FloatLabeledEntry.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'	GrouPlay.iOS			

Im getting this error in build when i try to deploy on real iphone device.
when i tried to deploy on simulator it works. 

what can be the problem?

**Comment by erickriva** [comment]
Usually this can be fixed by reinstalling the package 'FloatLabeledEntry', cleaning iOS project and rebuilding.

**Comment by erickriva** [comment]
Seems that is all okay, then this issue will be closed.
If needed, you can reopen in near future.
